name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for'
        required: true
        default: '2.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify plugin files
        run: |
          ls -la main.js manifest.json styles.css

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            tag="${{ github.event.inputs.tag }}"
          else
            tag="${GITHUB_REF#refs/tags/}"
          fi

          gh release create "$tag" \
            --title="$tag" \
            --generate-notes \
            main.js manifest.json styles.css
