name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify plugin files
        run: |
          ls -la main.js manifest.json styles.css

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --generate-notes \
            main.js manifest.json styles.css
